package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/ericgrandt/gqlgen-example/graph/generated"
	"github.com/ericgrandt/gqlgen-example/graph/model"
)

// CreateTest is the resolver for the createTest field.
func (r *mutationResolver) CreateTest(ctx context.Context, input string) (*model.Test, error) {
	panic(fmt.Errorf("not implemented: CreateTest - createTest"))
}

// User is the resolver for the user field.
func (r *testResolver) User(ctx context.Context, obj *model.Test) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Test returns generated.TestResolver implementation.
func (r *Resolver) Test() generated.TestResolver { return &testResolver{r} }

type testResolver struct{ *Resolver }
