package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"crypto/rand"
	"math/big"

	"github.com/ericgrandt/gqlgen-example/graph/generated"
	"github.com/ericgrandt/gqlgen-example/graph/model"
	"github.com/ericgrandt/gqlgen-example/middleware"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (model.Todo, error) {
	randNumber, _ := rand.Int(rand.Reader, big.NewInt(10000))
	todo := model.Todo{
		Text:   input.Text,
		ID:     randNumber.String(),
		UserID: middleware.GetUserContext(ctx).ID,
	}

	stmt, err := r.db.Prepare("INSERT INTO todo(id, value, user_id) VALUES (?, ?, ?)")
	if err != nil {
		panic(err)
	}

	_, err = stmt.Exec(todo.ID, todo.Text, todo.UserID)
	if err != nil {
		panic(err)
	}

	return todo, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context, pageSize int32, pageNum int32) ([]model.Todo, error) {
	stmt, _ := r.db.Prepare("SELECT * FROM todo WHERE user_id = ? LIMIT ? OFFSET ?")
	defer stmt.Close()

	user := middleware.GetUserContext(ctx)
	rows, _ := stmt.Query(user.ID, pageSize, pageSize*(pageNum-1))
	var todos []model.Todo
	for rows.Next() {
		var todo model.Todo
		rows.Scan(&todo.ID, &todo.UserID, &todo.Text)
		todos = append(todos, todo)
	}
	return todos, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (model.User, error) {
	return r.userData.GetUser(obj.UserID)
}

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type todoResolver struct{ *Resolver }
